# -*- coding: utf-8 -*-
"""keplerGL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OXkr5IjeAV-kqXqYUk9ahSW0jP_tUm2C

# Interactive Geospatial Visualization: KeplerGL and Jupyter Notebook

from https://www.coursera.org/learn/geospatial-keplergl-jupyter/supplement/MhGNK/project-based-course-overview
"""

!pip install geopandas
!pip install keplergl

import pandas as pd
import geopandas as gpd
from keplergl import KeplerGl

from google.colab import output
output.enable_custom_widget_manager()

#Create a basemap 
m = KeplerGl(height=600, width=800)

#show the map
m

# Create a Dataframe
df = pd.DataFrame(
    {
        "City": ["Shanghai", "Sao paulo", "Cairo", "London", "Toronto", "Sydney"],
        "Country": ["China", "Brazil", "Egypt", "England", "Canada", "Australia"],
        "Latitude": [31.045556, -23.473293, 30.05, 51.514125, 43.666667, -33.861481],
        "Longitude": [121.399722, -46.665803, 31.25, -0.093689, -79.416667, 151.205475],
        "Population": [14608512, 10021437, 7734602, 7421228, 4612187, 4394585],
    }
)


df

m = KeplerGl(height=600, width=800)
m.add_data(data=df, name='cities')

m

# parking violations data

parking_df = pd.read_csv("https://raw.githubusercontent.com/eisenerz108/Aman_GIS_KeplerGL_ParkingSpots_Philadelphia/main/data/parking_violations_2015.csv")
parking_df.head()

parking_df.shape

parking_df.dropna(subset=["lat", "lon"], how='all', inplace=True)

parking_df.shape

gdf = gpd.GeoDataFrame(parking_df, geometry=gpd.points_from_xy(parking_df.lon, parking_df.lat), crs="EPSG:4326")
gdf.head()

gdf.to_file("parking_2015.geojson",  driver='GeoJSON')

m = KeplerGl(height=900)
m.add_data(data=gdf, name='parking_points')
m

"""## 3D Hex"""

gdf = gpd.read_file("parking_2015.geojson")
gdf.head()

m = KeplerGl(height=900)
m.add_data(data=gdf, name='3dHexagon')
m

"""## Animation"""

gdf = gpd.read_file("parking_2015.geojson", parse_dates=True)
gdf["issue_datetime"] = pd.to_datetime(gdf["issue_datetime"], dayfirst=True)

gdf.sample(10)

m = KeplerGl(height=900)
m.add_data(data=gdf, name='animation')
m

"""## Choropleth Map"""

neighborhoods = gpd.read_file("https://raw.githubusercontent.com/eisenerz108/Aman_GIS_KeplerGL_ParkingSpots_Philadelphia/main/data/neighbrhoods.geojson")
neighborhoods.head()

neighborhoods.crs

neighborhoods = neighborhoods.to_crs("EPSG:4326")

m = KeplerGl(height=900)
m.add_data(data=neighborhoods, name='choropleth_map')
m



