# -*- coding: utf-8 -*-
"""Covid Geospatial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uhgQgycoP2MRo68k3vBj9CzdlSPbQmnt

Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gpd
import contextily as ctx
import matplotlib.pyplot as plt

"""# Data: COVID by region

data-by-region/jrc-covid-19-all-days-by-regions.csv

URL: https://raw.githubusercontent.com/ec-jrc/COVID-19/master/data-by-region/jrc-covid-19-all-days-by-regions.csv

*Numbers of confirmed cases, hospitalized cases, recoveries, and deaths due to COVID-19 in Europe, by date, country and region.*
"""

url = "https://raw.githubusercontent.com/ec-jrc/COVID-19/master/data-by-region/jrc-covid-19-all-days-by-regions.csv"
df = pd.read_csv(url)
df.head()

"""Explorting the Dataset"""

df.shape

df.info()

df.Date.min()

df.Date.max()

"""# Geodataframe"""

df.dropna(axis=0, subset=["lat", "lon"], inplace=True)

crs = "EPSG:4326"

gdf = gpd.GeoDataFrame(df, crs=crs, geometry=gpd.points_from_xy(df.lon, df.lat))
gdf.head()

"""## Plotting"""

fig, ax = plt.subplots(figsize=(12,10))
gdf[gdf["Date"] == "2020-03-02"].to_crs(epsg=3857).plot(ax=ax, color="Red", edgecolor="white")
ctx.add_basemap(ax,source=ctx.providers.Stamen.TonerLite)
plt.title("Deceased Map: March 2, 2020")
plt.axis("off");

"""# Bubble Map"""

fig, ax = plt.subplots(figsize=(12,10))
gdf[gdf["Date"] == "2020-03-30"].to_crs(epsg=3857).plot(markersize="CumulativeDeceased", alpha=0.4, ax=ax,color="Red", edgecolor="white")
ctx.add_basemap(ax,source=ctx.providers.Stamen.TonerLite)
plt.title("Deceased Map: March 30, 2020")
plt.axis("off");

gdf["normalized_death"] = ((gdf["CumulativeDeceased"] - gdf["CumulativeDeceased"].min()) / (gdf["CumulativeDeceased"].max() - gdf["CumulativeDeceased"].min()))*100

gdf.head()

fig, ax = plt.subplots(figsize=(12,10))
gdf[gdf["Date"] == "2021-03-30"].to_crs(epsg=3857).plot(markersize="normalized_death", alpha=0.4, ax=ax,color="Red", edgecolor="white")
ctx.add_basemap(ax,source=ctx.providers.Stamen.TonerLite)
plt.title("Deceased Map: March 30, 2020")
plt.axis("off");

"""# Join & Merge

Data for EU: polygon, polyline and point topology

https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts
"""

path = "NUTS_RG_01M_2021_4326.geojson"
eu = gpd.read_file(path)
eu.head()

eu.plot("CNTR_CODE", figsize=(12,10))

import rtree, pygeos

sjoined = gpd.sjoin(gdf,eu,op="within")
sjoined.head()

